language: node_js
node_js:
  - "6.5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
before_script:
  - psql -c 'create database insights_test;' -U postgres
before_install:
  - pip install --user codecov
  - $CXX --version
after_success:
  - codecov --file coverage/lcov.info --disable search
